# GBA 6070 - Programming Foundation for Business Analytics
# Dr. Mohammad Salehan
# Assignment 8 - Multidimensioal Arrays
Runt the cell below to set up your notebook. Each cell should start with np.random.seed(0) to make the results consistent for all students.

In [6]:
import numpy as np
np.random.seed(0)

1. Create a 4x4 array that contains numbers 1-16.

In [5]:
array = np.arange(1, 17).reshape(4, 4)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


2. Create 2 random 4x3 arrays and calculate the sum of their crrosponding elements. Use vectorization for sum calculation.

In [22]:
array1 = np.random.randint(0, 10, (4, 3))
array2 = np.random.randint(0, 10, (4, 3))

sum_array = array1 + array2
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nSum of corresponding elements:\n", sum_array)

Array 1:
 [[7 8 1]
 [2 1 1]
 [7 5 0]
 [4 1 1]]

Array 2:
 [[6 6 0]
 [2 3 7]
 [9 2 4]
 [9 0 6]]

Sum of corresponding elements:
 [[13 14  1]
 [ 4  4  8]
 [16  7  4]
 [13  1  7]]


3. Create 2 normally distributed (mean=0, std_dev=1) random 10x5 arrays, stack them vertically, then calculate the average of each column. Use vectorization.

In [13]:
array1 = np.random.randint(0, 10, (10, 5))
array2 = np.random.randint(0, 10, (10, 5))

stacked_array = np.vstack((array1, array2))

column_means = np.mean(stacked_array, axis=0)

print("Stacked Array:\n", stacked_array)
print("\nAverage of Each Column:\n", column_means)

Stacked Array:
 [[9 3 7 5 5]
 [8 0 8 3 6]
 [9 3 2 7 0]
 [3 0 3 6 1]
 [9 2 9 4 9]
 [1 3 2 4 9]
 [7 4 9 4 1]
 [2 7 2 3 9]
 [7 6 6 2 3]
 [6 0 8 0 7]
 [6 5 9 6 5]
 [2 7 1 9 2]
 [2 5 6 4 2]
 [2 1 0 9 0]
 [2 8 3 0 8]
 [8 1 0 5 8]
 [2 3 5 3 8]
 [6 4 6 3 6]
 [2 6 5 5 9]
 [4 6 5 1 3]]

Average of Each Column:
 [4.85 3.7  4.8  4.15 5.05]


4. Create a normally distributed (mean=0, std_dev=1) random 10x5 array, then calculate the sum of the values in each row. Use vectorization.

In [52]:
array = np.random.normal(0, 1, (10, 5))

row_sums = np.sum(array, axis=1)

print("10x5 Normally Distributed Array:\n", array)
print("\nSum of Each Row:\n", row_sums)

10x5 Normally Distributed Array:
 [[ 1.35146445  1.76342238 -0.62237488 -0.55015916 -2.19540892]
 [-0.34610799  0.46748685 -1.49079178  0.18028515  1.12860016]
 [ 0.26920185  0.50479393 -0.04387922  0.05890549 -1.78270813]
 [ 1.07138216 -0.33658259  1.63659924 -1.07684777 -0.26487929]
 [ 1.36155521 -1.18014331  3.2357412   1.48368638 -1.31481072]
 [ 0.86905759  0.97162559  1.34492068 -0.66900325 -0.2039615 ]
 [-0.25186539 -0.12684306  0.794597   -0.12893418  1.72536705]
 [ 0.53445963  1.30514006  0.02706297 -0.0499425   0.27420048]
 [-0.29936119 -1.07569633  0.1260749   0.35266393 -0.1057083 ]
 [-1.96648239 -0.44335792 -1.63262548  1.41026516  1.11976457]]

Sum of Each Row:
 [-0.25305613 -0.06052761 -0.99368609  1.02967175  3.58602877  2.31263911
  2.01232142  2.09092064 -1.00202699 -1.51243606]


5. Create a 5x3 array initialized with random integers 1-10, then reshape it to 3x5, and then calculate its sum (single number fo sum). Use vectorization.

In [26]:
array = np.random.randint(1, 11, (5, 3))
reshaped_array = array.reshape(3, 5)
sum_array = np.sum(reshaped_array)

print("Original 5x3 Array:\n", array)
print("\nReshaped 3x5 Array:\n", reshaped_array)
print("\nTotal Sum of All Elements:", sum_array)

Original 5x3 Array:
 [[ 3  5  9]
 [ 3 10  9]
 [ 8  9  3]
 [ 4  4  7]
 [ 1  4  7]]

Reshaped 3x5 Array:
 [[ 3  5  9  3 10]
 [ 9  8  9  3  4]
 [ 4  7  1  4  7]]

Total Sum of All Elements: 86


6. Create a 5x3 array initialized with random integers 1-10, then multiply each value by 2. Use vectorization.

In [24]:
array = np.random.randint(1, 11, (5, 3))
doubled_array = array * 2

print("Original Array:\n", array)
print("\nDoubled Array:\n", doubled_array)

Original Array:
 [[ 5  2  8]
 [ 5  1  3]
 [ 8  5  1]
 [ 3  7 10]
 [ 3  5 10]]

Doubled Array:
 [[10  4 16]
 [10  2  6]
 [16 10  2]
 [ 6 14 20]
 [ 6 10 20]]
